### ISSUE TITLE
cant use replace in queue mode

### ISSUE THREAD

**Issue by georgkrause** [ahlstromcj/sequencer64#74] opened 2017-04-25 10:37 UTC
What i do:

* start queue mode with \
* try to replace running pattern with replace_mod + pattern_key

expected:

after the current cycly, only the toggled pattern should run

what happens:

all running pattern still run + the toggled pattern

**Comment by Animtim** [comment] 2017-04-25 10:54
I can confirm this, I already added this in my notes ("Replace doesn't work with queue") but didn't file a bug report yet.

**Comment by ahlstromcj** [comment] 2017-04-26 10:08
Thanks, will start working on this soon.  Meanwhile, get the latest master for important fixes.  Won't close those issues until thoroughly tested (by me or you guys :-).

**Comment by georgkrause** [comment] 2017-04-27 05:03
@ahLstromcj could you mark issues which need testing by a lable? I lost the overview :(

**Comment by ahlstromcj** [comment] 2017-04-30 20:41
Okay, this scenario plays out just the same in seq24.  While replace mode does a "turn on pattern on, turn the rest off" without queue mode in force, all it does with queue mode on  is queue the selected pattern and then turn it on, leaving the other patterns untouched.

However, queuing a "replace" does seem like a good feature, so I will look into coding this feature to work, if not in "--legacy" (seq24) mode.  Might take a little while, as I have a lot of features/fixes roiling through my brain right now.

Georg, I will eventually get to those labels  :-)

**Comment by georgkrause** [comment] 2017-05-01 10:58
@ahlstromcj thanks for thinking about this feature! In fact the current behavior makes sense in some way, but for me it felt like a bug.

**Comment by Animtim** [comment] 2017-05-05 21:01
Tested wip branch, replace now works fine with queue mode :)
I just noticed a small visual bug, when combining replace and snapshot. If there's a playing pattern not finished yet when the replace happens, and I restore the snapshot before it finishes, the pattern keep showing the grey queue rectangle on it.

Also, is it intentional that now, when using the replace shortcut again on the same pattern, it restores the previous patterns on top of the new one? That's a very interesting feature, kind of a "solo snapshot". Could be actually useful to have same behaviour with regular not-queued replace.

**Comment by ahlstromcj** [comment] 2017-05-06 11:45
I will look into your questions.  Currently, I'm debugging a couple of nits in the process, while documenting the new feature in the "cja" branch of the sequencer-doc project.  For some reason, when moving from screen-set 0 to screen-set 1, playback freezes when the replace key is hit.  Weird, though convenient for making a screenshot :-D.

And yet, I meant to be able to toggle the solo feature, as that seems useful.

**Comment by ahlstromcj** [comment] 2017-05-06 13:48
Okay, got the basics working, still need to follow up on the other points.  Note that the queued-solo/queued-replace functionality applies only to the current screen-set.  Any patterns playing on other screen-sets should not be affected, should keep playing.  Anyway, see latest wip.  By the way, the freeze happened because I was access illegal values in the screen-set array :-D

**Comment by ahlstromcj** [comment] 2017-05-06 19:09
Geez, found more bugs in queued-replace, two more commits to wip!

**Comment by Animtim** [comment] 2017-05-06 20:03
Tested quickly with those two more commits, and found a new bug now. Try using replace in queue mode once on one pattern. Then use it on another pattern: you can see it mixes "previous-patterns" with the new replacing pattern. Try doing it on several patterns one after the other, and you'll end with most patterns playing and never stopped when using replace.

I would say the "memory" when using replace should be restored only when using replace again on the same pattern, and it should be cleared if one use replace on another pattern.

**Comment by ahlstromcj** [comment] 2017-05-06 20:16
Probably a good idea.  Right now, you have to "clear" the memory by exiting keep-queue mode (by clicking the normal queue key, and then re-establish keep-queue by clicking the keep-queue key again.  Would also try to add the non-queued replace toggling at that point as well.

I'll probably work on it tomorrow, and quit for today.  Thanks for all the help!

**Comment by Animtim** [comment] 2017-05-06 20:36
Yes, I figured this current workaround to clear the replace memory. Ok, sounds like a good plan.
Note to be more clear, I should have said:  "..., and it should be cleared AND take a new "snapshot" if one use replace on another pattern." 
Cheers!

**Comment by ahlstromcj** [comment] 2017-05-07 13:57
Okay, the changes are in place in wip.  Seems to do what you want.

Also updated sequencer64-doc, in the cja branch, and found a way to optimize the PDF.

**Comment by ahlstromcj** [comment] 2017-05-07 17:10
Merged wip into master, will consider this closed, and await any new issue related to this one.  Version 0.90.5 is official.

**Closed by ahlstromcj** 2017-05-07 17:10 UTC
Labels: needs testing

**Comment by Animtim** [comment] 2017-05-07 17:53
Thanks a lot, works perfectly as I expected :)

**Comment by georgkrause** [comment] 2017-06-01 09:08
same here, sorry for the delay!
